/** Screen capabilities, not 38 duplicate page components. Planned routes are not served. */
export const SCREEN_ARCHITECTURE = [
  {
    number: 1,
    name: "Splash",
    route: "/middle",
    surface: "welcome",
    status: "integrated",
  },
  {
    number: 2,
    name: "Welcome",
    route: "/middle/welcome",
    surface: "welcome",
    status: "implemented",
  },
  {
    number: 3,
    name: "Login / Sign Up",
    route: "/middle/login",
    surface: "Sites sign-in + RoleSelection",
    status: "implemented",
  },
  {
    number: 4,
    name: "OTP",
    route: null,
    surface: "external identity provider",
    status: "deferred",
  },
  {
    number: 5,
    name: "Role Selection",
    route: "/middle/roles",
    surface: "RoleSelection",
    status: "implemented",
  },
  {
    number: 6,
    name: "Profile",
    route: "/middle/profile",
    surface: "AccountView",
    status: "implemented",
  },
  {
    number: 7,
    name: "Owner Dashboard",
    route: "/middle/analytics",
    surface: "AccountView",
    status: "partial",
  },
  {
    number: 8,
    name: "Add Property",
    route: "/middle/add",
    surface: "InventoryForm",
    status: "implemented",
  },
  {
    number: 9,
    name: "Property Type",
    route: "/middle/add",
    surface: "InventoryForm field",
    status: "integrated",
  },
  {
    number: 10,
    name: "Location",
    route: "/middle/add",
    surface: "InventoryForm field",
    status: "integrated",
  },
  {
    number: 11,
    name: "Property Details",
    route: "/middle/add",
    surface: "InventoryForm fields",
    status: "integrated",
  },
  {
    number: 12,
    name: "Media Upload",
    route: null,
    surface: "private media service",
    status: "deferred",
  },
  {
    number: 13,
    name: "AI Review",
    route: null,
    surface: "Lilith structured review",
    status: "deferred",
  },
  {
    number: 14,
    name: "Agent Dashboard",
    route: "/middle/analytics",
    surface: "AccountView",
    status: "partial",
  },
  {
    number: 15,
    name: "Add Requirement",
    route: "/middle/add",
    surface: "InventoryForm",
    status: "implemented",
  },
  {
    number: 16,
    name: "Budget & Location",
    route: "/middle/add",
    surface: "InventoryForm fields",
    status: "integrated",
  },
  {
    number: 17,
    name: "Requirement Details",
    route: "/middle/add",
    surface: "InventoryForm fields",
    status: "integrated",
  },
  {
    number: 18,
    name: "AI Requirement Summary",
    route: null,
    surface: "Lilith structured summary",
    status: "deferred",
  },
  {
    number: 19,
    name: "Discover",
    route: "/middle/discover",
    surface: "Discover + PropertyCard",
    status: "implemented",
  },
  {
    number: 20,
    name: "Property Detail",
    route: "/middle/properties/:id",
    surface: "PropertyDetail",
    status: "partial",
  },
  {
    number: 21,
    name: "Why Match",
    route: "/middle/discover",
    surface: "PropertyCard reasons",
    status: "integrated",
  },
  {
    number: 22,
    name: "Pass",
    route: "/middle/discover",
    surface: "PropertyCard action",
    status: "integrated",
  },
  {
    number: 23,
    name: "Interested",
    route: "/middle/discover",
    surface: "PropertyCard action",
    status: "integrated",
  },
  {
    number: 24,
    name: "Super Match",
    route: "/middle/discover",
    surface: "PropertyCard action",
    status: "integrated",
  },
  {
    number: 25,
    name: "It's a Match",
    route: "/middle/matches",
    surface: "mutual consent panel",
    status: "integrated",
  },
  {
    number: 26,
    name: "Match Inbox",
    route: "/middle/matches",
    surface: "MatchInbox",
    status: "implemented",
  },
  {
    number: 27,
    name: "Deal Room",
    route: "/middle/deals/:id",
    surface: "DealRoom",
    status: "partial",
  },
  {
    number: 28,
    name: "Lilith Deal Assistant",
    route: null,
    surface: "Lilith assistant panel",
    status: "deferred",
  },
  {
    number: 29,
    name: "Schedule Viewing",
    route: "/middle/deals/:id",
    surface: "DealRoom Viewing",
    status: "integrated",
  },
  {
    number: 30,
    name: "Viewing Confirmed",
    route: "/middle/deals/:id",
    surface: "DealRoom Viewing",
    status: "integrated",
  },
  {
    number: 31,
    name: "Offer / Negotiation",
    route: null,
    surface: "DealRoom Offer",
    status: "deferred",
  },
  {
    number: 32,
    name: "Deal Timeline",
    route: "/middle/deals/:id",
    surface: "DealRoom Timeline",
    status: "integrated",
  },
  {
    number: 33,
    name: "Deal Success",
    route: null,
    surface: "closing workflow",
    status: "deferred",
  },
  {
    number: 34,
    name: "0.1% Fee",
    route: null,
    surface: "fee policy and ledger",
    status: "domain-only",
  },
  {
    number: 35,
    name: "Receipt / Deal Record",
    route: null,
    surface: "settlement record",
    status: "deferred",
  },
  {
    number: 36,
    name: "Analytics",
    route: "/middle/analytics",
    surface: "AccountView counts",
    status: "partial",
  },
  {
    number: 37,
    name: "Notifications",
    route: "/middle/notifications",
    surface: "NotificationList",
    status: "implemented",
  },
  {
    number: 38,
    name: "Trust Center / Profile",
    route: "/middle/profile",
    surface: "AccountView",
    status: "partial",
  },
] as const;
