import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const leads = sqliteTable("leads", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  contact: text("contact"),
  source: text("source").notNull(),
  budget: integer("budget").notNull(),
  budgetPeriod: text("budget_period"),
  area: text("area").notNull(),
  propertyType: text("property_type"),
  bedrooms: integer("bedrooms"),
  moveDate: text("move_date"),
  viewingWindow: text("viewing_window"),
  contractTerm: text("contract_term"),
  preferredLanguage: text("preferred_language"),
  customerCountry: text("customer_country"),
  dealIntent: text("deal_intent"),
  wechat: text("wechat"),
  partnerAgency: text("partner_agency"),
  partnerAgent: text("partner_agent"),
  partnerContact: text("partner_contact"),
  externalId: text("external_id"),
  importBatch: text("import_batch"),
  pets: text("pets"),
  requirements: text("requirements"),
  consentAt: text("consent_at"),
  spamSignal: text("spam_signal"),
  stage: text("stage").notNull(),
  nextFollowUpAt: text("next_follow_up_at"),
  updatedAt: text("updated_at"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
});
